[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
mpl_core_auction = "T8Bk6U2jRGNkqDqtvjGvKGqBzvurwx7gTdmag6jQupL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha --parallel -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.genesis]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"  
program = "tests/programs/metaplex_core_program.so"
