[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "22DF9UYSTGrV7UMfEs1bUqcwScCFqNFYMqVZHxQ7ZW52"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
